save_path: "/tmp/data/"
enable_logging: True
log_to_file: True
log_path: "/tmp/"
log_level: "info"
# Supported log levels:
# "debug", "info", "warning", "error", "critical"
# Recommended log level : "info"
